In [1]:
from datasets import load_dataset


ds = load_dataset("geekyrakshit/indian-legal-acts")

d:\Capstone Project - Legal Aid for Marginalised Communities\legal-aid-assistant-\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Generating central split: 100%|██████████| 883/883 [00:00<00:00, 5088.42 examples/s]
Generating andaman_and_nicobar_islands split: 100%|██████████| 66/66 [00:00<00:00, 2765.34 examples/s]
Generating andhra_pradesh split: 100%|██████████| 323/323 [00:00<00:00, 8639.06 examples/s]
Generating arunachal_pradesh split: 100%|██████████| 1111/1111 [00:00<00:00, 25028.45 examples/s]

In [2]:
print(ds.keys())

dict_keys(['central', 'andaman_and_nicobar_islands', 'andhra_pradesh', 'arunachal_pradesh'])

In [3]:
print(ds)  # ds is your loaded dataset object

DatasetDict({
    central: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 883
    })
    andaman_and_nicobar_islands: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 66
    })
    andhra_pradesh: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 323
    })
    arunachal_pradesh: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 1111
    })
})

In [4]:
# For example, inspect 'central'
import pandas as pd
central_df = pd.DataFrame(ds['central'])
print(central_df.head())
print(central_df.info())   # column types and missing values
print(central_df.describe())  # summary stats for numeric columns (if any)

  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Enactment Date  883 non-null    object
 1   Act Number      883 non-null    object
 2   Short Title     883 non-null    object
 3   View            883 non-null    object
 4   Entity          883 non-null    object
 5   Markdown        881 non-null    object
dtypes: object(6)
memory usage: 41.5+ KB
None
       Enactment Date Act Number                       Short Title  \
count             883        883                               883
unique            739         85                               882
top       23-Jun-2005         30  The Powers-of Attorney Act, 1882
freq                6         24                                 2

                                                     View   Entity  \
count                                                 883      883
unique                                                881        1
top     https://www.indiacode.nic.in/bitstream/1234567...  central
freq                                                    2      883

                                                 Markdown
count                                                 881
unique                                                881
top     # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
freq                                                    1

In [5]:
# Access one key (say central)
import pandas as pd
df_central = pd.DataFrame(ds['central'])
print(df_central.head(5))

  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...

In [6]:
for key in ds.keys():
    print(f"Columns in {key}: {ds[key].column_names}")

Columns in central: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in andaman_and_nicobar_islands: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in andhra_pradesh: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in arunachal_pradesh: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']

In [7]:
all_dfs = [pd.DataFrame(ds[key]) for key in ds.keys()]
full_df = pd.concat(all_dfs, ignore_index=True)
print(full_df.shape)
print(full_df.head())

(2383, 6)
  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...

In [8]:
full_df = full_df.dropna(subset=['Markdown'])
print(full_df.shape)

(2378, 6)

In [9]:
print(full_df.isnull().sum())

Enactment Date    0
Act Number        0
Short Title       0
View              0
Entity            0
Markdown          0
dtype: int64

In [10]:
full_df.head(10)

,Enactment Date,Act Number,Short Title,View,Entity,Markdown
0,14-Mar-1838,05,"The Bengal Bonded Warehouse Association Act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,# THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1,27-Aug-1838,19,"The Coasting vessels Act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE COASTING-VESSELS ACT, 1838\n __________\..."
2,18-Mar-1839,07,"The Madras Rent and Revenue Sales Act, 1839",https://www.indiacode.nic.in/bitstream/1234567...,central,"THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\..."
3,28-Oct-1842,13,"The Revenue, Bombay, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE REVENUE, BOMBAY, 1842\n __________\n\n A..."
4,16-Dec-1842,17,"The Revenue Commissioners, Bombay Act, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\..."
5,7-Jan-1846,03,"The Boundary-Marks, Bombay 1846",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE BOUNDARY-MARKS, BOMBAY 1846\n\nACT NO. I..."
6,23-Sep-1848,20,"The Bengal Land Holder's Attendance Act, 1848",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE BENGAL LAND HOLDER’ ATTENDANCE ACT, 1848..."
7,26-May-1849,10,"The Madras Board of Revenue,1849",https://www.indiacode.nic.in/bitstream/1234567...,central,# MADRAS.—BOARD OF REVENUE.\n\n ACT NO. X OF 1...
8,14-Jun-1850,25,"The Forfeited Deposits Act, 1850",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE FORFEITED DEPOSITS ACT, 1850\n\n## _____..."
9,21-Jun-1850,26,"The Improvements in Towns Act, 1850",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE IMPROVEMENTS IN TOWNS ACT, 1850\n\nACT N..."

In [11]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces
    text = re.sub(r'<.*?>', '', text)  # remove HTML tags
    return text

full_df['Markdown'] = full_df['Markdown'].apply(clean_text)
full_df['Short Title'] = full_df['Short Title'].apply(clean_text)

In [12]:
full_df['Enactment Date'] = pd.to_datetime(full_df['Enactment Date'], errors='coerce')

In [13]:
full_df.head(5)

,Enactment Date,Act Number,Short Title,View,Entity,Markdown
0,1838-03-14,05,"the bengal bonded warehouse association act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,# the bengal bonded warehouse association act ...
1,1838-08-27,19,"the coasting vessels act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the coasting-vessels act, 1838 __________ ar..."
2,1839-03-18,07,"the madras rent and revenue sales act, 1839",https://www.indiacode.nic.in/bitstream/1234567...,central,"the madras rent and revenue sales act, 1839 __..."
3,1842-10-28,13,"the revenue, bombay, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the revenue, bombay, 1842 __________ act no...."
4,1842-12-16,17,"the revenue commissioners, bombay act, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the revenue commissioners, bombay act, 1842 ..."

In [14]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# -------------------------------
# 2️⃣ Prepare the data
# We'll combine 'Short Title' and 'Markdown' for embeddings
full_df['text_to_embed'] = full_df['Short Title'] + " " + full_df['Markdown']

# Optional: keep metadata (like Enactment Date, Act Number, View link, Entity)
metadata_list = full_df[['Enactment Date','Act Number','Short Title','View','Entity']].to_dict(orient='records')

# -------------------------------
# 3️⃣ Load the embedding model
model = SentenceTransformer('all-mpnet-base-v2')  # free and strong

# -------------------------------
# 4️⃣ Generate embeddings
texts = full_df['text_to_embed'].tolist()
embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

# -------------------------------
# 5️⃣ Create FAISS index
dimension = embeddings.shape[1]  # 768 for mpnet
index = faiss.IndexFlatL2(dimension)  # L2 distance index
index.add(embeddings)  # add vectors

print(f"Number of vectors in index: {index.ntotal}")

# -------------------------------
# 6️⃣ Define a search function
def semantic_search(query, k=5):
    # Embed the query
    query_vec = model.encode([query], convert_to_numpy=True)
    
    # Search in FAISS
    distances, indices = index.search(query_vec, k)
    
    # Return results with metadata
    results = []
    for i, idx in enumerate(indices[0]):
        result = {
            "score": float(distances[0][i]),
            "text": texts[idx],
            "metadata": metadata_list[idx]
        }
        results.append(result)
    return results

# -------------------------------
# 7️⃣ Test search
query = "acts related to revenue in Bombay"
results = semantic_search(query, k=3)
for r in results:
    print("\nScore:", r['score'])
    print("Short Title + Markdown:", r['text'][:300], "...")
    print("Metadata:", r['metadata'])

Batches: 100%|██████████| 75/75 [00:34<00:00,  2.17it/s]

Number of vectors in index: 2378

Score: 0.4985072612762451
Short Title + Markdown: the revenue, bombay, 1842 # the revenue, bombay, 1842 __________ act no.13 of 1842 _________ _passed by the hon’ble the president of the council of india in council, on the 28[th] of october, 1842, with_ _the assent of the right hon’ble the governor general of india._ an act to enable the holders of ...
Metadata: {'Enactment Date': Timestamp('1842-10-28 00:00:00'), 'Act Number': '13', 'Short Title': 'the revenue, bombay, 1842', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/18945/1/a1842-13.pdf', 'Entity': 'central'}

Score: 0.5169731378555298
Short Title + Markdown: the revenue commissioners, bombay act, 1842 # the revenue commissioners, bombay act, 1842 act no. 17 of 1842. _----------------------------_ _passed by the hon’ble the president of the council of india in council, on the 16th of december, 1842,_ _with the assent of the right hon’ble the governor gen ...
Metadata: {'Enactment Date': Timestamp('1842-12-16 00:00:00'), 'Act Number': '17', 'Short Title': 'the revenue commissioners, bombay act, 1842', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/18946/1/a1842-17.pdf', 'Entity': 'central'}

Score: 0.6153470277786255
Short Title + Markdown: the taxation laws (continuation and validation of recovery proceedings) act, 1964 # the taxation laws (continuation and validation of recovery proceedings) act, 1964 __________ arrangement of sections __________ sections 1. short title. 2. definitions. 3. continuation and validation of certain proce ...
Metadata: {'Enactment Date': Timestamp('1964-05-12 00:00:00'), 'Act Number': '11', 'Short Title': 'the taxation laws (continuation and validation of recovery proceedings) act, 1964', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/1427/2/A1964-11.pdf', 'Entity': 'central'}

In [15]:
import numpy as np
import pickle
import faiss
import os

# Make folder for saved files
save_dir = "vector_store"
os.makedirs(save_dir, exist_ok=True)

# Paths
embeddings_path = os.path.join(save_dir, "embeddings.npy")
faiss_index_path = os.path.join(save_dir, "legal_acts_index.faiss")
metadata_path = os.path.join(save_dir, "metadata.pkl")

# --- Save ---
np.save(embeddings_path, embeddings)
faiss.write_index(index, faiss_index_path)
pickle.dump(metadata_list, open(metadata_path, "wb"))

print("✅ All saved successfully!")
print(f"Files stored in: {os.path.abspath(save_dir)}")

✅ All saved successfully!
Files stored in: d:\Capstone Project - Legal Aid for Marginalised Communities\legal-aid-assistant-\capstone_project\vector_store

In [16]:
import numpy as np
import pickle
import faiss
import os

# Folder path
save_dir = "vector_store"

# Load
faiss_index_path = os.path.join(save_dir, "legal_acts_index.faiss")
metadata_path = os.path.join(save_dir, "metadata.pkl")

index = faiss.read_index(faiss_index_path)
metadata_list = pickle.load(open(metadata_path, "rb"))

print(f"Loaded index with {index.ntotal} vectors.")

Loaded index with 2378 vectors.

In [17]:
from sentence_transformers import SentenceTransformer


# Load the same model used for embeddings
model = SentenceTransformer('all-mpnet-base-v2')

def retrieve_texts(query, k=5):
    query_vec = model.encode([query], convert_to_numpy=True)
    distances, indices = index.search(query_vec, k)

    results = []
    for i, idx in enumerate(indices[0]):
        item = metadata_list[idx].copy()
        item["score"] = float(distances[0][i])
        results.append(item)
    return results

In [18]:
def build_prompt(query, retrieved_docs):
    context = ""
    for doc in retrieved_docs:
        # No need to access doc['metadata'] — fields are already at top level
        context += (
            f"Act: {doc.get('Short Title', 'Unknown')}\n"
            f"Enactment Date: {doc.get('Enactment Date', 'N/A')}\n"
            f"Entity: {doc.get('Entity', 'N/A')}\n"
            f"View: {doc.get('View', 'N/A')}\n"
            f"Score: {doc.get('score', 'N/A')}\n\n"
        )

    prompt = f"""
You are a legal assistant AI. 
Use the following acts and information to answer the query accurately.

Context:
{context}

Query: {query}

Answer:
"""
    return prompt.strip()

In [19]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from dotenv import load_dotenv
import os

load_dotenv()

model_name = "meta-llama/Llama-2-7b-hf"
hf_token = os.getenv("LLAMA_HF_TOKEN")

tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
llm = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    dtype=torch.float16,
    token=hf_token
)

Loading checkpoint shards: 100%|██████████| 2/2 [00:16<00:00,  8.48s/it]

In [20]:
def generate_response(query):
    retrieved = retrieve_texts(query, k=3)
    prompt = build_prompt(query, retrieved)

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = llm.generate(**inputs, max_new_tokens=300)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return answer

In [21]:
query = "acts related to revenue in Bombay?"
retrieved_docs = retrieve_texts(query)


print(retrieved_docs)

[{'Enactment Date': Timestamp('1842-10-28 00:00:00'), 'Act Number': '13', 'Short Title': 'the revenue, bombay, 1842', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/18945/1/a1842-13.pdf', 'Entity': 'central', 'score': 0.6723916530609131}, {'Enactment Date': Timestamp('1842-12-16 00:00:00'), 'Act Number': '17', 'Short Title': 'the revenue commissioners, bombay act, 1842', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/18946/1/a1842-17.pdf', 'Entity': 'central', 'score': 0.7410169243812561}, {'Enactment Date': Timestamp('1849-05-26 00:00:00'), 'Act Number': '10', 'Short Title': 'the madras board of revenue,1849', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/19544/1/a1849-10.pdf', 'Entity': 'central', 'score': 0.7699805498123169}, {'Enactment Date': Timestamp('2015-01-17 00:00:00'), 'Act Number': '2', 'Short Title': 'the andhra pradesh value added tax (amendment) act, 2005.', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/3904/1/ACT%20NO%2002-2015.pdf', 'Entity': 'Andhra Pradesh', 'score': 0.7748991250991821}, {'Enactment Date': Timestamp('1856-08-23 00:00:00'), 'Act Number': '18', 'Short Title': 'the calcutta land-revenue act, 1856', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/19028/1/A1856-18.pdf', 'Entity': 'central', 'score': 0.7824181914329529}]

In [22]:
prompt = build_prompt(query, retrieved_docs)
print(prompt)

You are a legal assistant AI.
Use the following acts and information to answer the query accurately.

Context:
Act: the revenue, bombay, 1842
Enactment Date: 1842-10-28 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18945/1/a1842-13.pdf
Score: 0.6723916530609131

Act: the revenue commissioners, bombay act, 1842
Enactment Date: 1842-12-16 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18946/1/a1842-17.pdf
Score: 0.7410169243812561

Act: the madras board of revenue,1849
Enactment Date: 1849-05-26 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/19544/1/a1849-10.pdf
Score: 0.7699805498123169

Act: the andhra pradesh value added tax (amendment) act, 2005.
Enactment Date: 2015-01-17 00:00:00
Entity: Andhra Pradesh
View: https://www.indiacode.nic.in/bitstream/123456789/3904/1/ACT%20NO%2002-2015.pdf
Score: 0.7748991250991821

Act: the calcutta land-revenue act, 1856
Enactment Date: 1856-08-23 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/19028/1/A1856-18.pdf
Score: 0.7824181914329529



Query: acts related to revenue in Bombay?

Answer:

In [23]:
answer = generate_response(query)
print(answer)

You are a legal assistant AI.
Use the following acts and information to answer the query accurately.

Context:
Act: the revenue, bombay, 1842
Enactment Date: 1842-10-28 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18945/1/a1842-13.pdf
Score: 0.6723916530609131

Act: the revenue commissioners, bombay act, 1842
Enactment Date: 1842-12-16 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18946/1/a1842-17.pdf
Score: 0.7410169243812561

Act: the madras board of revenue,1849
Enactment Date: 1849-05-26 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/19544/1/a1849-10.pdf
Score: 0.7699805498123169



Query: acts related to revenue in Bombay?

Answer:

Act: the revenue, bombay, 1842
Enactment Date: 1842-10-28 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18945/1/a1842-13.pdf
Score: 0.7410169243812561

Act: the revenue commissioners, bombay act, 1842
Enactment Date: 1842-12-16 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/123456789/18946/1/a1842-17.pdf
Score: 0.7699805498123169

Act: the madras board of revenue,1849
Enactment Date: 1849-05-26 00:00:00
Entity: central
View: https://www.indiacode.nic.in/bitstream/12345

In [24]:

from datasets import load_dataset

df_new = load_dataset("viber1/indian-law-dataset")

In [25]:
print(df_new.keys())

dict_keys(['train'])

In [26]:
print(df_new)

DatasetDict({
    train: Dataset({
        features: ['Instruction', 'Response'],
        num_rows: 24607
    })
})

In [27]:
# print(df_new)                # Overview of dataset splits
print(df_new['train'].column_names)  # Column names
print(df_new['train'][0])    # Inspect first example

['Instruction', 'Response']
{'Instruction': 'What is the difference between a petition and a plaint in Indian law?', 'Response': "A petition is a formal request submitted to a courttribunalor authority to seek a specific remedy or relief. It is commonly used for various purposessuch as filing a writ petition in the High Court or submitting a petition for divorce. On the other handa plaint is a formal written statement of a plaintiff's claim in a civil lawsuit. The key difference is that a petition is more versatile and can be used for various legal matterswhile a plaint is specific to civil cases."}

In [28]:
import os
import pickle
import numpy as np
import faiss
import pandas as pd
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

# -------------------------------
# 2️⃣ Preprocess new dataset
# Combine Instruction + Response
# -------------------------------
df_new = df_new['train'].to_pandas()

df_new['text_to_embed'] = df_new['Instruction'] + " " + df_new['Response']

# Optional metadata
metadata_new = df_new[['Instruction', 'Response']].to_dict(orient='records')
texts_new = df_new['text_to_embed'].tolist()

# -------------------------------
# 3️⃣ Load embedding model
# -------------------------------
model = SentenceTransformer('all-mpnet-base-v2')

# -------------------------------
# 4️⃣ Generate embeddings for new data
# -------------------------------
embeddings_new = model.encode(texts_new, show_progress_bar=True, convert_to_numpy=True)
print("✅ New embeddings shape:", embeddings_new.shape)

# -------------------------------
# 5️⃣ Load previous FAISS index, embeddings, metadata
# -------------------------------
save_dir = "vector_store"
embeddings_path = os.path.join(save_dir, "embeddings.npy")
faiss_index_path = os.path.join(save_dir, "legal_acts_index.faiss")
metadata_path = os.path.join(save_dir, "metadata.pkl")

# Load old data
embeddings_old = np.load(embeddings_path)
index_old = faiss.read_index(faiss_index_path)
metadata_old = pickle.load(open(metadata_path, "rb"))

print("Old embeddings shape:", embeddings_old.shape)
print("Old FAISS index size:", index_old.ntotal)

# -------------------------------
# 6️⃣ Merge old + new embeddings and metadata
# -------------------------------

Batches: 100%|██████████| 769/769 [01:03<00:00, 12.04it/s]

✅ New embeddings shape: (24607, 768)
Old embeddings shape: (2378, 768)
Old FAISS index size: 2378

In [29]:
# Merge embeddings
combined_embeddings = np.vstack([embeddings_old, embeddings_new])

# Merge metadata
combined_metadata = metadata_old + metadata_new

# Merge texts safely
texts_old_combined = [
    f"{m.get('Short Title','')} {m.get('Act Number','')} {m.get('View','')}" 
    for m in metadata_old
]
texts_new_combined = texts_new
combined_texts = texts_old_combined + texts_new_combined

# Create FAISS index
dimension = combined_embeddings.shape[1]
index_combined = faiss.IndexFlatL2(dimension)
index_combined.add(combined_embeddings)
print("✅ Combined FAISS index size:", index_combined.ntotal)

✅ Combined FAISS index size: 26985

In [30]:
# Inspect first item in old metadata
print(metadata_old[0])

{'Enactment Date': Timestamp('1838-03-14 00:00:00'), 'Act Number': '05', 'Short Title': 'the bengal bonded warehouse association act, 1838', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/19097/1/a1838-5.pdf', 'Entity': 'central'}

In [31]:
np.save(os.path.join(save_dir, "combined_embeddings.npy"), combined_embeddings)
faiss.write_index(index_combined, os.path.join(save_dir, "combined_legal_index.faiss"))
with open(os.path.join(save_dir, "combined_metadata.pkl"), "wb") as f:
    pickle.dump(combined_metadata, f)

print(f"✅ Combined FAISS + metadata saved to {os.path.abspath(save_dir)}")

✅ Combined FAISS + metadata saved to d:\Capstone Project - Legal Aid for Marginalised Communities\legal-aid-assistant-\capstone_project\vector_store

In [32]:
def semantic_search(query, k=5):
    query_vec = model.encode([query], convert_to_numpy=True)
    distances, indices = index_combined.search(query_vec, k)
    
    results = []
    for i, idx in enumerate(indices[0]):
        result = {
            "score": float(distances[0][i]),
            "text": combined_texts[idx],
            "metadata": combined_metadata[idx]
        }
        results.append(result)
    return results

In [33]:
query = "law"
results = semantic_search(query, k=2)

for r in results:
    print("\nScore:", r['score'])
    print("Text snippet:", r['text'][:300], "...")
    print("Metadata:", r['metadata'])

Score: 1.0083551406860352
Text snippet: the damodaram sanjivayya national law university act, 2008 32 https://www.indiacode.nic.in/bitstream/123456789/16255/1/act_no_32_of_2008.pdf ...
Metadata: {'Enactment Date': Timestamp('2008-09-24 00:00:00'), 'Act Number': '32', 'Short Title': 'the damodaram sanjivayya national law university act, 2008', 'View': 'https://www.indiacode.nic.in/bitstream/123456789/16255/1/act_no_32_of_2008.pdf', 'Entity': 'Andhra Pradesh'}

Score: 1.0608551502227783
Text snippet: How many laws are mentioned in this passage? There are three laws mentioned in this passage. ...
Metadata: {'Instruction': 'How many laws are mentioned in this passage?', 'Response': 'There are three laws mentioned in this passage.'}

In [34]:
from sentence_transformers import SentenceTransformer
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# -------------------------------
# Load embedding model (same as before)
# -------------------------------
embedding_model = SentenceTransformer('all-mpnet-base-v2')

# -------------------------------
# Use the combined FAISS index & metadata
# -------------------------------
# index_combined, combined_metadata, combined_texts from previous pipeline

def retrieve_texts(query, k=5):
    """Retrieve top-k relevant documents from combined FAISS index."""
    query_vec = embedding_model.encode([query], convert_to_numpy=True)
    distances, indices = index_combined.search(query_vec, k)

    results = []
    for i, idx in enumerate(indices[0]):
        # copy metadata and add score
        item = combined_metadata[idx].copy()
        item["score"] = float(distances[0][i])
        results.append(item)
    return results

In [35]:
def retrieve_texts_1(query, k=5):
    """Retrieve top-k relevant documents from combined FAISS index with deduplication."""
    query_vec = embedding_model.encode([query], convert_to_numpy=True)
    distances, indices = index_combined.search(query_vec, k*2)  # fetch extra in case of duplicates

    results = []
    seen_texts = set()

    for i, idx in enumerate(indices[0]):
        text = combined_texts[idx].strip()
        if text in seen_texts:
            continue  # skip duplicate
        seen_texts.add(text)
        
        # copy metadata and add score
        item = combined_metadata[idx].copy()
        item["score"] = float(distances[0][i])
        results.append(item)
        
        if len(results) >= k:
            break  # stop when we have k unique documents

    return results

In [43]:
def build_prompt(query, retrieved_docs):
    """
    Build a dynamic prompt for LLM using retrieved documents.
    The prompt adapts to the query type:
    - Comparison/difference → structured side-by-side answer
    - Elaboration/explanation → detailed descriptive answer
    """
    # Build context from retrieved docs
    context = ""
    for doc in retrieved_docs:
        context += (
            f"Title/Instruction: {doc.get('Short Title', doc.get('Instruction', 'Unknown'))}\n"
            f"Enactment Date: {doc.get('Enactment Date', 'N/A')}\n"
            f"Entity: {doc.get('Entity', 'N/A')}\n"
            f"View/PDF: {doc.get('View', doc.get('Response', 'N/A'))}\n"
            f"Score: {doc.get('score', 'N/A')}\n\n"
        )

    # Dynamic instruction to LLM
    prompt = f"""
You are a knowledgeable legal assistant AI.

Use the following documents to answer the query accurately. 
Your response should match the nature of the query:

- If the query asks for a difference or comparison, provide a structured side-by-side answer.
- If the query asks for elaboration, explanation, or details, provide a clear descriptive answer.
- Always base your answer only on the provided context. 
- Optionally cite the relevant Titles/Instructions from the context.
- Key Differences: Summarize the main distinctions in a few sentences.
- Remove duplicate points and keep the answer concise.

Context:
{context}

Query: {query}

Answer:
"""
    return prompt.strip()

In [44]:
model_name = "meta-llama/Llama-2-7b-hf"
hf_token = os.getenv("LLAMA_HF_TOKEN")

tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
llm = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    dtype=torch.float16,
    token=hf_token
)

# -------------------------------
# Generate response function
# -------------------------------
def generate_response_1(query, k=5, max_tokens=300):
    """Fetch top-k docs, build prompt, and generate LLM response."""
    retrieved = retrieve_texts_1(query, k=k)
    prompt = build_prompt(query, retrieved)

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = llm.generate(**inputs, max_new_tokens=max_tokens)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return answer

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  3.71it/s]
Some parameters are on the meta device because they were offloaded to the cpu.

In [1]:
query = "What is the difference between a writ petition and a public interest litigation (PIL) in India "
answer = generate_response_1(query, k=5)
print(answer)

NameError: name 'generate_response_1' is not defined