In [ ]:
from datasets import load_dataset

ds = load_dataset("geekyrakshit/indian-legal-acts")

:

In [2]:
print(ds.keys())

dict_keys(['central', 'andaman_and_nicobar_islands', 'andhra_pradesh', 'arunachal_pradesh'])

In [3]:
print(ds)  # ds is your loaded dataset object

DatasetDict({
    central: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 883
    })
    andaman_and_nicobar_islands: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 66
    })
    andhra_pradesh: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 323
    })
    arunachal_pradesh: Dataset({
        features: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown'],
        num_rows: 1111
    })
})

In [4]:
# For example, inspect 'central'
import pandas as pd
central_df = pd.DataFrame(ds['central'])
print(central_df.head())
print(central_df.info())   # column types and missing values
print(central_df.describe())  # summary stats for numeric columns (if any)

  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Enactment Date  883 non-null    object
 1   Act Number      883 non-null    object
 2   Short Title     883 non-null    object
 3   View            883 non-null    object
 4   Entity          883 non-null    object
 5   Markdown        881 non-null    object
dtypes: object(6)
memory usage: 41.5+ KB
None
       Enactment Date Act Number                       Short Title  \
count             883        883                               883
unique            739         85                               882
top       23-Jun-2005         30  The Powers-of Attorney Act, 1882
freq                6         24                                 2

                                                     View   Entity  \
count                                                 883      883
unique                                                881        1
top     https://www.indiacode.nic.in/bitstream/1234567...  central
freq                                                    2      883

                                                 Markdown
count                                                 881
unique                                                881
top     # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
freq                                                    1

In [5]:
# Access one key (say central)
import pandas as pd
df_central = pd.DataFrame(ds['central'])
print(df_central.head(5))

  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...

In [6]:
for key in ds.keys():
    print(f"Columns in {key}: {ds[key].column_names}")

Columns in central: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in andaman_and_nicobar_islands: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in andhra_pradesh: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']
Columns in arunachal_pradesh: ['Enactment Date', 'Act Number', 'Short Title', 'View', 'Entity', 'Markdown']

In [7]:
all_dfs = [pd.DataFrame(ds[key]) for key in ds.keys()]
full_df = pd.concat(all_dfs, ignore_index=True)
print(full_df.shape)
print(full_df.head())

(2383, 6)
  Enactment Date Act Number  \
0    14-Mar-1838         05
1    27-Aug-1838         19
2    18-Mar-1839         07
3    28-Oct-1842         13
4    16-Dec-1842         17

                                         Short Title  \
0  The Bengal Bonded Warehouse Association Act, 1838
1                     The Coasting vessels Act, 1838
2        The Madras Rent and Revenue Sales Act, 1839
3                          The Revenue, Bombay, 1842
4        The Revenue Commissioners, Bombay Act, 1842

                                                View   Entity  \
0  https://www.indiacode.nic.in/bitstream/1234567...  central
1  https://www.indiacode.nic.in/bitstream/1234567...  central
2  https://www.indiacode.nic.in/bitstream/1234567...  central
3  https://www.indiacode.nic.in/bitstream/1234567...  central
4  https://www.indiacode.nic.in/bitstream/1234567...  central

                                            Markdown
0  # THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1  # THE COASTING-VESSELS ACT, 1838\n __________\...
2  THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\...
3  # THE REVENUE, BOMBAY, 1842\n __________\n\n A...
4  # THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\...

In [8]:
full_df = full_df.dropna(subset=['Markdown'])
print(full_df.shape)

(2378, 6)

In [9]:
print(full_df.isnull().sum())

Enactment Date    0
Act Number        0
Short Title       0
View              0
Entity            0
Markdown          0
dtype: int64

In [10]:
full_df.head(10)

,Enactment Date,Act Number,Short Title,View,Entity,Markdown
0,14-Mar-1838,05,"The Bengal Bonded Warehouse Association Act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,# THE BENGAL BONDED WAREHOUSE ASSOCIATION ACT\...
1,27-Aug-1838,19,"The Coasting vessels Act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE COASTING-VESSELS ACT, 1838\n __________\..."
2,18-Mar-1839,07,"The Madras Rent and Revenue Sales Act, 1839",https://www.indiacode.nic.in/bitstream/1234567...,central,"THE MADRAS RENT AND REVENUE SALES ACT, 1839\n\..."
3,28-Oct-1842,13,"The Revenue, Bombay, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE REVENUE, BOMBAY, 1842\n __________\n\n A..."
4,16-Dec-1842,17,"The Revenue Commissioners, Bombay Act, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE REVENUE COMMISSIONERS, BOMBAY ACT, 1842\..."
5,7-Jan-1846,03,"The Boundary-Marks, Bombay 1846",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE BOUNDARY-MARKS, BOMBAY 1846\n\nACT NO. I..."
6,23-Sep-1848,20,"The Bengal Land Holder's Attendance Act, 1848",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE BENGAL LAND HOLDER’ ATTENDANCE ACT, 1848..."
7,26-May-1849,10,"The Madras Board of Revenue,1849",https://www.indiacode.nic.in/bitstream/1234567...,central,# MADRAS.—BOARD OF REVENUE.\n\n ACT NO. X OF 1...
8,14-Jun-1850,25,"The Forfeited Deposits Act, 1850",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE FORFEITED DEPOSITS ACT, 1850\n\n## _____..."
9,21-Jun-1850,26,"The Improvements in Towns Act, 1850",https://www.indiacode.nic.in/bitstream/1234567...,central,"# THE IMPROVEMENTS IN TOWNS ACT, 1850\n\nACT N..."

In [11]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces
    text = re.sub(r'<.*?>', '', text)  # remove HTML tags
    return text

full_df['Markdown'] = full_df['Markdown'].apply(clean_text)
full_df['Short Title'] = full_df['Short Title'].apply(clean_text)

In [12]:
full_df['Enactment Date'] = pd.to_datetime(full_df['Enactment Date'], errors='coerce')

In [13]:
full_df.head(5)

,Enactment Date,Act Number,Short Title,View,Entity,Markdown
0,1838-03-14,05,"the bengal bonded warehouse association act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,# the bengal bonded warehouse association act ...
1,1838-08-27,19,"the coasting vessels act, 1838",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the coasting-vessels act, 1838 __________ ar..."
2,1839-03-18,07,"the madras rent and revenue sales act, 1839",https://www.indiacode.nic.in/bitstream/1234567...,central,"the madras rent and revenue sales act, 1839 __..."
3,1842-10-28,13,"the revenue, bombay, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the revenue, bombay, 1842 __________ act no...."
4,1842-12-16,17,"the revenue commissioners, bombay act, 1842",https://www.indiacode.nic.in/bitstream/1234567...,central,"# the revenue commissioners, bombay act, 1842 ..."

In [38]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# -------------------------------
# 2️⃣ Prepare the data
# We'll combine 'Short Title' and 'Markdown' for embeddings
full_df['text_to_embed'] = full_df['Short Title'] + " " + full_df['Markdown']

# Optional: keep metadata (like Enactment Date, Act Number, View link, Entity)
metadata_list = full_df[['Enactment Date','Act Number','Short Title','View','Entity']].to_dict(orient='records')

# -------------------------------
# 3️⃣ Load the embedding model
model = SentenceTransformer('all-mpnet-base-v2')  # free and strong

# -------------------------------
# 4️⃣ Generate embeddings
texts = full_df['text_to_embed'].tolist()
embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

# -------------------------------
# 5️⃣ Create FAISS index
dimension = embeddings.shape[1]  # 768 for mpnet
index = faiss.IndexFlatL2(dimension)  # L2 distance index
index.add(embeddings)  # add vectors

print(f"Number of vectors in index: {index.ntotal}")

# -------------------------------
# 6️⃣ Define a search function
def semantic_search(query, k=5):
    # Embed the query
    query_vec = model.encode([query], convert_to_numpy=True)
    
    # Search in FAISS
    distances, indices = index.search(query_vec, k)
    
    # Return results with metadata
    results = []
    for i, idx in enumerate(indices[0]):
        result = {
            "score": float(distances[0][i]),
            "text": texts[idx],
            "metadata": metadata_list[idx]
        }
        results.append(result)
    return results

# -------------------------------
# 7️⃣ Test search
query = "acts related to revenue in Bombay"
results = semantic_search(query, k=3)
for r in results:
    print("\nScore:", r['score'])
    print("Short Title + Markdown:", r['text'][:300], "...")
    print("Metadata:", r['metadata'])

RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
module 'torch' has no attribute '_utils'

In [ ]:
import numpy as np
import pickle
import faiss
import os

# Make folder for saved files
save_dir = "vector_store"
os.makedirs(save_dir, exist_ok=True)

# Paths
embeddings_path = os.path.join(save_dir, "embeddings.npy")
faiss_index_path = os.path.join(save_dir, "legal_acts_index.faiss")
metadata_path = os.path.join(save_dir, "metadata.pkl")

# --- Save ---
np.save(embeddings_path, embeddings)
faiss.write_index(index, faiss_index_path)
pickle.dump(metadata_list, open(metadata_path, "wb"))

print("✅ All saved successfully!")
print(f"Files stored in: {os.path.abspath(save_dir)}")

✅ All saved successfully!
Files stored in: d:\Capstone Project - Legal Aid for Marginalised Communities\legal-aid-assistant-\capstone_project\vector_store

In [16]:
import numpy as np
import pickle
import faiss
import os

# Folder path
save_dir = "vector_store"

# Load
faiss_index_path = os.path.join(save_dir, "legal_acts_index.faiss")
metadata_path = os.path.join(save_dir, "metadata.pkl")

index = faiss.read_index(faiss_index_path)
metadata_list = pickle.load(open(metadata_path, "rb"))

print(f"Loaded index with {index.ntotal} vectors.")

Loaded index with 2378 vectors.

In [ ]:
from sentence_transformers import SentenceTransformer


# Load the same model used for embeddings
model = SentenceTransformer('all-mpnet-base-v2')

def retrieve_texts(query, k=5):
    query_vec = model.encode([query], convert_to_numpy=True)
    distances, indices = index.search(query_vec, k)

    results = []
    for i, idx in enumerate(indices[0]):
        item = metadata_list[idx].copy()
        item["score"] = float(distances[0][i])
        results.append(item)
    return results

:

In [33]:
def build_prompt(query, retrieved_docs):
    context = ""
    for doc in retrieved_docs:
        meta = doc['metadata']
        context += f"Act: {meta['Short Title']}\nDetails: {meta}\n\n"
    
    prompt = f"""
You are a legal assistant AI. 
Use the following acts and information to answer the query accurately.

Context:
{context}

Query: {query}

Answer:
"""
    return prompt.strip()

In [34]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "meta-llama/Llama-2-7b-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)
llm = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)

def generate_response(query):
    retrieved = retrieve_texts(query, k=3)
    prompt = build_prompt(query, retrieved)

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = llm.generate(**inputs, max_new_tokens=300)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return answer

OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-2-7b-hf.
401 Client Error. (Request ID: Root=1-68ec9dd4-63841ce252381c9738dd2857;7e48c1fa-8268-49b6-bbb2-f62b460efc43)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-hf/resolve/main/config.json.
Access to model meta-llama/Llama-2-7b-hf is restricted. You must have access to it and be authenticated to access it. Please log in.

In [35]:
import torch
print(torch.__file__)

d:\Capstone Project - Legal Aid for Marginalised Communities\legal-aid-assistant-\venv\lib\site-packages\torch\__init__.py

In [29]:
import torch
print(torch.__version__)
# print(torch.version) # Remove or comment out the incorrect line

# If you want to print the version again, use the correct attribute:
# print(f"PyTorch version: {torch.__version__}")

2.4.1+cu121

In [ ]:
print("Hello")